### ISSUE TITLE
Support for Multi-colored Nicknames

### ISSUE THREAD

**Issue by sylv256** [exaskye/Drogtor#14]
Perhaps you could add support for complex-styled nicknames? This would make this mod a viable alternative to Styled Nicknames, which obviously wouldn't work with Drogtor.

**Comment by sylv256** [comment]
I tested Drogtor with Styled nicknames, and it seems Styled Nicknames takes precedence over this mod's `/nick` command.

**Comment by exaskye** [comment]
I consider Drogtor obsolete in favor of Styled Nicknames. Drogtor is designed to be a dead-simple nickname mod, and it was created in early 1.16 when alternatives were not readily available. All of the mods in the PlaceholderAPI ecosystem massively outdo Drogtor in every way imaginable; if I had my way, Drogtor would not be ported past 1.17, as it has long since been irrelevant.

It additionally has multiple bugs when combined with other mods that modify player names and associated data, such as the "Modder Modder" bug at ModFest: Singularity. It was designed in a vacuum to be used alone.

Drogtor is in feature freeze. If you want these features, please use Styled Nicknames. Switchy recently gained support for it.
