### ISSUE TITLE
Nicknames in Commands

### ISSUE THREAD

**Issue by poombus** [exaskye/Drogtor#5]
I don't know if it's because of the way the mod is structured, but nicknames and commands don't mix well together.

Let's say player "poombus" was nicknamed "joe," and I wanted to TP him. MCs autofill recognizes "poombus" as "joe," so I write "tp joe ~ ~500 ~". But this actually doesn't work because the game recognizes the player as "joe," but is still expecting "poombus."

Now normally, this is just an inconvenience, if anything. It can be easily ignored by ignoring autofill and writing "tp poombus ~ ~500 ~". It's just I'm using Scarpet, the Carpet Mod (by gnembon)'s "programming" language. The thing about that is, it too only recognizes players by their nickname. And as far as I know, there is no way to find a player's actual username without avoiding Drogtor's function altogether.

What I request is that the nicknames are purely cosmetic, but don't change how the server sees them. I don't if this is possible or if it'll be too tedious, but if it's not too much trouble, it would be appreciated. :)

**Comment by exaskye** [comment]
Ah, this is likely an unintentional side-effect of the namecard weirdness. If you use `/namecard poombus` it should fix the disconnect...

**Comment by exaskye** [comment]
(The "namecard weirdness" modifies the player packets sent to the client and lies about the player's username, so as far as the client is concerned, your nickname *is* your namecard. There's not really any other way to accomplish this on vanilla clients, unfortunately. I should probably add a config option to disable this since it's often more troublesome than it's worth, and on a modded server you can instead install Fabrication and enable fixes.use_player_list_name_in_tag)

**Comment by poombus** [comment]
Ah! Thanks for the fix. I just so happen to be running Fabrication as well, so this is a relief.

**Comment by exaskye** [comment]
Drogtor is in feature freeze and has been obsoleted by the PlaceholderAPI ecosystem, including Styled Nicknames. If you still want this, I encourage you to check if Styled Nicknames meets your needs, and if not, to request this feature over there.
